### ISSUE TITLE
Native Zone_IsClientInZone not working

### ISSUE THREAD

**Issue by danielsartor** [Franc1sco/DevZones#6]
I tried to verify:

if (Zone_IsClientInZone(client, "AntiCampAll", false, false))

I changed the name of the thirdparty zone to AntiCampAll and didn't use a team anticamp as it was before (AntiCampCT and AntiCampT), just a general  and it was working, but if a client is inside a zone and he teleports away from it, it doesn't detect that he left it, then I wanted to verify, before slaying, if he is inside the same zone.

**Comment by Totenfluch** [comment]
#7 fixes this.

**Comment by danielsartor** [comment]
I will check. Thanks (:

**Comment by danielsartor** [comment]
Fixed. @Totenfluch I just noticed the translation when creating the zone to restart the creation is in another language :x
